### ISSUE TITLE
ORBNET Streaming Engine Settings Window

### ISSUE THREAD

**Issue by mrdx-orb** [ORBNETSYS/StreamingEngine-Public#3]
The application window should have the title "ORBNET Streaming Engine Settings"

The ORBNET logo should include ORBNET Systems.

The application window opens maybe 10 pixels too short and shows a scroll bar. 

Change settings from the taskbar can be opened more than once, this voids settings changes when updated as the change is reverted to default when you close the second window.

Milestone Basic User Password should be covered with asterisk.

**Comment by mrdx-orb** [comment]
Same for Password Manager just relating to width and can be opened more than once.

**Comment by EricBourque** [comment]
Done. It will not be possible to show the password. It is still in clear text in the xml file.
