### ISSUE TITLE
Taskbar Manager can open more than once

### ISSUE THREAD

**Issue by mrdx-orb** [ORBNETSYS/StreamingEngine-Public#5]
Can open Streaming Engine Taskbar manager more than once.

<img width="187" alt="Capture" src="https://user-images.githubusercontent.com/92920127/154271692-ac756bbc-83b1-45cd-9dea-419dbe40c00c.PNG">

**Comment by mrdx-orb** [comment]
When you run the Streaming Engine Manager from the desktop shortcut can this first kill the Streaming Engine Manager process before it opens again. To ensure it opens for the user who wants to see this in the taskbar.

**Comment by EricBourque** [comment]
Hi Miles, we have a choice to make here. Unlike Milestone, we can have a tray app open for each user. If a user opens it several times it should not have a any negative effects.
